### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by dinhanhx** [ddowd97/Morphing#3]
With `requirements.txt` other people can just `pip install -r requirements.txt`

```
pyqt5
scipy
numpy
imageio
mathplotlib
```

[Read more](https://pip.pypa.io/en/stable/user_guide/#requirements-files)

**Comment by ddowd97** [comment]
Thanks for this! I didn't know something like this was so easily done with pip.
I've now added a requirements.txt and updated the project's readme file for any newcomers.

I feel that this is also a good place to note that the numpy/scipy packages have run into bugs with recent updates to Windows 10 (which can't be fixed for a little while), so the file enforces that the installed version of numpy is no greater than 1.19.3 for now.

**Comment by dinhanhx** [comment]
Just saying, here is my requirements.txt for this repos. I also perceived the fmod() numpy issue on Windows. 
```
cycler==0.10.0
imageio==2.9.0
kiwisolver==1.3.1
matplotlib==3.3.3
numpy==1.19.3
Pillow==8.0.1
pyparsing==2.4.7
PyQt5==5.15.1
PyQt5-sip==12.8.1
python-dateutil==2.8.1
scipy==1.5.4
six==1.15.0
```
